# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-modified',), 'verbose_name_plural': 'entries'},
        ),
    ]
